name: Deployment pipeline

on:
  push:
    branches: [main]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Test if can set custom name for public action
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      # - run: npm run eslint
      - name: Check style
        run: npm run eslint

